[app]
  port = ":8086"
  read_timeout = 10000 # in ms
  write_timeout = 65000 # in ms

[log]
  level = "debug"
  fileLevel = "error"
  outputFile = "app.log"

[mysql]
  dbName = "local_transfer_proj_db"
  maxIdleConn = 10
  maxOpenConn = 50
  user = "root"
  pass = ""
  host = "127.0.0.1"
  port = "3306"