[log]
  level = "debug"
  fileLevel = "error"
  outputFile = "app.log"

[mysql]
  dbName = "local_transfer_proj_db"
  maxIdleConn = 10
  maxOpenConn = 50
  user = "root"
  pass = "pass"
  host = "127.0.0.1"
  port = "3336"
